// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EHostels.Data.Models;

public partial class RefreshToken
{
    public long EntityId { get; set; }

    public long UserId { get; set; }

    public string Token { get; set; }

    public DateTime ExpiredAt { get; set; }

    public bool IsExpired { get; set; }

    public DateTime CreatedOn { get; set; }

    public virtual User User { get; set; }
}